language: python

python:
  - "2.7"
  - "3.4"

matrix:
  include:
  - python: "2.7"
    env: TEST_SUITE=suite_2_7
  - python: "3.4"
    env: TEST_SUITE=suite_3_4
  - python: "pypy"
    env: TEST_SUITE=suite_pypy
script: ECHO $TEST_SUITE


#command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -r test_requirements.txt
  - pip install --extra-index-url https://testpypi.python.org/simple coveralls

script:
    - pushd package
    - python setup.py develop
    - popd
    - python runtests.py --with-coverage  --cover-package=package --exclude setup.py

after_success:
    - coveralls


