language: python
python:
    - "2.7"

#command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -r test_requirements.txt
  - pip install -r package/requirements.txt --extra-index-url https://testpypi.python.org/simple
  - pip install coveralls

script:
    - pushd package
    - python setup.py develop
    - popd
    - python runtests.py --with-coverage  --cover-package=package --exclude setup.py

after_success:
    - coveralls


